# 服务器前置任务(ubuntu使用)
- name: tensorflow
  hosts: tensorflow
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt-get -y install python


# # 核心任务

- name: tensorflow
  hosts: tensorflow
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: tensorflow, tags: "tensorflow"}